repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # keep ruff version in sync with .github/workflows/ci.yml
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        language_version: python3
  
  - repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in .pre-commit-config.yaml
    rev: v2.4.1
    hooks:
    - id: codespell
