# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

data:
  study:
    source:
      name: Scherer2015Individually
    split:
      name: PredefinedSplit
      test_split_query: "session == '1'"
      col_name: split
      valid_split_by: _index
      valid_split_ratio: 0.1
      valid_random_state: 33
  target:
    =replace=: true
    name: LabelEncoder
    event_types: Stimulus
    event_field: code
    return_one_hot: true
    aggregation: trigger
  trigger_event_type: Stimulus
  start: 3.0
  duration: 4.0
  summary_columns: [code]
brain_model_output_size: &brain_model_output_size 5
trainer_config.monitor: val/bal_acc
trainer_config.mode: max
trainer_config.patience: 15
trainer_config.n_epochs: 100
lightning_optimizer_config.optimizer.lr: 5.0e-4
lightning_optimizer_config.scheduler.kwargs.max_lr: 5.0e-4
loss:
  name: CrossEntropyLoss
metrics: !!python/object/apply:neuralbench.defaults.metrics.get_classification_metric_configs
  - *brain_model_output_size
